repos:
  - repo: local
    hooks:
      - id: pipenv-format
        name: pipenv run format
        entry: pipenv run format
        language: system
        pass_filenames: false
        stages: [commit]

      - id: pipenv-lint
        name: pipenv run lint
        entry: pipenv run lint
        language: system
        pass_filenames: false
        stages: [commit]